name: CI
permissions:
  contents: read

on:
  pull_request:
    branches:
      - master

jobs:
  unit:
    name: Unit ${{ matrix.job_index }}
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      matrix:
        job_index: [0, 1, 2]
    env:
      CI: true

    steps:
      - uses: actions/checkout@v2
      - name: Use Node 22
        uses: actions/setup-node@v5
        with:
          node-version: 22
      - name: Install
        run: yarn
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test --jobsTotal=3 --jobsIndex=${{ matrix.job_index }}

  single-unit:
    name: Unit
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      CI: true

    steps:
      - uses: actions/checkout@v2
      - name: Use Node 22
        uses: actions/setup-node@v5
        with:
          node-version: 22
      - name: Install
        run: yarn
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test

  merge-checks-complete:
      runs-on: ubuntu-latest
      needs: [unit, single-unit]
      steps:
          - name: merge-checks-complete
            run: echo 0